name: GitHub Actions Demo
on: [push]
jobs:
  Checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@V3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.9'

      - name: requirements
        run : |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: checkin
        run: |
          python sockboom.py
      - run: echo "🍏 This job's status is ${{ job.status }}."
