name: GitHub Actions Demo
#on: [push]
on:
  push:
  schedule:
    - cron: '5 * * * *' # UTC+8小时=北京时间 17代表凌晨一点
jobs:
  Checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: checkin
        run: |
          python sockboom.py
          python ssr.py
          python xiaohouzi_fzy.py
      - name: Push log #更新日志
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: test
          push_options: --force
      - run: echo "🍏 This job's status is ${{ job.status }}.yess"
