name: GitHub Actions Demo
on: [push]
jobs:
  Checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.9'

      - name: requirements
        run : |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: checkin
        run: |
          python sockboom.py
      - name: Push log #更新日志
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: test
      - run: echo "🍏 This job's status is ${{ job.status }}."
