name: 'Auto check in sockboom'

on: 
  schedule:
    - cron: '17 1,8,12,18,22 * * *' # UTC+8小时=北京时间 17代表凌晨一点
  watch:
    types: [started]
   
jobs:
  checking:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai          

    - name: Chickin Api #签到
      run: | 
        python sockboom.py
        tail run.log #避免日志上传失败丢失日志
    - name: Push log #更新日志
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: auto-checkin
        branch: master
